config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  get 'my_portfolio', to: 'users#my_portfolio'
  devise_for :users
  root 'welcome#index'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'friendships#my_friends'
  get 'search_friends', to: 'friendships#search'
  resources :friendships, only: [:destroy, :create]
  resources :users, only: [:show]
  get 'all_stocks', to: 'stocks#all_stocks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def self.get_all_stocks
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_key], endpoint: 'https://sandbox.iexapis.com/v1')
    client.stock_market_list(:mostactive)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.getprice(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_key], endpoint: 'https://sandbox.iexapis.com/v1')
        begin
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
    end

    def self.has_stock(ticker_symbol)
        where(ticker: ticker_symbol).first
    end

    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  
  def stock_alredy_tracked?(ticker_symbol)
    stock = Stock.has_stock(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_alredy_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = ( first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end
  
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def already_friend?(friend_id)
    self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:index]
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    def my_friends
        @friends = current_user.friends
    end

    def search
        if params[:search].present?
            @search = User.search(params[:search])
            @search = current_user.except_current_user(@search)
                if !@search.empty?
                    respond_to do |format|
                        format.js { render partial: 'friendships/result' }
                    end
                else
                    respond_to do |format|
                        flash.now[:alert] = "No user found"
                        format.js { render partial: 'friendships/result' }
                    end
                end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a Name or Email to search"
                format.js { render partial: 'friendships/result' }
            end
        end
    end

    def create
        friend = User.find(params[:friend])
        @new_friend = Friendship.create(user: current_user, friend: friend)
        flash[:notice] = "You are now friends with User #{friend.first_name}"
        redirect_to my_friends_path
    end

    def destroy
        friend = User.find(params[:id])
        remove_friend = Friendship.where(user_id: current_user.id, friend_id: friend.id).first
        remove_friend.destroy
        flash[:notice] = "You stopped following #{friend.first_name}"
        redirect_to my_friends_path
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    def search
        if params[:stock].present?
            @stock = Stock.getprice(params[:stock])
            if @stock
                respond_to do |format|
                    format.js { render partial: 'users/result' }
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please enter a valid Symbol"
                    format.js { render partial: 'users/result' }
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a Symbol to search"
                format.js { render partial: 'users/result' }
            end
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

    def create
        stock = Stock.has_stock(params[:stock])
        if stock.blank?
            stock = Stock.getprice(params[:stock])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = " #{stock.ticker} was successfully removed from portfolio"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @stocks = Stock.get_all_stocks
        @list_stock = @stocks.each do |list_stock|
            list_stock
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_list-friend.html.erb
<div class="row">
    <div class="col-sm-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |friend| %>
                <tr>
                    <th scope="row"><%= friend.email %></th>
                    <td><%= friend.first_name %></td>
                    <td><%= friend.last_name %></td>
                    <td>
                        <%= link_to 'View Profile', user_path(friend), class: "btn btn-outline-success" %>
                        <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>

app/views/friendships/_result.html.erb
<div class="col-sm-6 noleftpadding">
    <%= render 'layouts/messages' %>
</div>

<div class="row mb-2">
	<% if @search %>
		<% @search.each do |search| %>
			<div class="col-sm-6 mb-3">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">Name: <%= search.full_name %></h5>
						<p class="card-text"><strong>Email: </strong><%= search.email %></p>
						<%= link_to 'View Profile', user_path(search), class: "btn btn-success" %>
						<% if current_user.already_friend?(search.id) %>
							<%= ' You are friends' %>
						<% else %>
							<%= link_to 'Follow friend?', friendships_path(friend: search), class: "btn btn-success", method: :post %>
						<% end %>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>	
</div>

app/views/friendships/_result.js.erb
document.querySelector('#search_results').innerHTML = "<%= j render 'friendships/result.html' %>"

app/views/friendships/my_friends.html.erb
<h1>Friends</h1>

<div class="search-area">
    <h3>Search Friends</h3> 
    <%= form_tag search_friends_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9">
                <%= text_field_tag :search, params[:search], placeholder: "Name or Email", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
<div id="search_results" class="error_msg">
</div>

<% if @friends.empty? %>
    <%=  'You are currently not friends with anyone' %>
<% else %>
    <%= render 'friendships/list-friend' %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if name == "notice" %>
        <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading"><%= notice %></h4>
        </div>
    <% else %>
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="alert-heading"><%= alert %></h4>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
    <%= link_to 'FinanceTracker', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if !user_signed_in? %>
      <%= link_to 'Sign up', new_user_registration_path, class: "nav-link ml-auto btn btn-primary" %>
      <%= link_to 'Login', user_session_path, class: "nav-link ml-2 btn btn-primary" %>
    <% end %>
    <% if current_user %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
          <%= link_to 'My portfolio', my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Friends', my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon 'user' %> Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit Profile
              <% end %>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav mr-4">
          <li class="nav-item">
          <i class="fa fa-user" aria-hidden="true"></i> <%= current_user.full_name %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="navbar-nav ml-3">
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
            
          </li>
        </ul>
      </div>
    <% end %> 
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <p></p> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-sm-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Last_Price</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @tracked_stocks.each do |stock| %>
                <tr>
                    <th scope="row"><%= stock.ticker.upcase %></th>
                    <td><%= stock.name %></td>
                    <td><%= stock.last_price %></td>
                    <td>
                        <% if current_user.id == @user.id %>
                           <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                        <% elsif current_user.can_track_stock?(stock.ticker) %>
                           <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, stock: stock.ticker), class: "btn btn-success", method: :post %>
                        <% else %>
                                You are already tracking
                                <% if !current_user.under_stock_limit? && !current_user.stock_alredy_tracked?(stock.ticker) %>
                                    10 stocks
                                <% end %>
                                <% if current_user.stock_alredy_tracked?(stock.ticker) %>
                                    this stock
                                <% end %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>

app/views/users/_result.html.erb
<div class="col-sm-6 noleftpadding">
    <%= render 'layouts/messages' %>
</div>


<% if @stock %>
    <div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Symbol: </strong><%= @stock.ticker.upcase %></li>
        <li class="list-group-item"><strong>Name: </strong><%= @stock.name %></li>
        <li class="list-group-item"><strong>Price: </strong><%= @stock.last_price %></li>
        <% if current_user.can_track_stock?(@stock.ticker) %>
            <li class="list-group-item"><%= link_to 'Add to portfolio', user_stocks_path(user: current_user, stock: @stock.ticker), class: "btn btn-success", method: :post %></li>
        <% else %>
            <li class="list-group-item">
                You are already tracking
                <% if !current_user.under_stock_limit? && !current_user.stock_alredy_tracked?(@stock.ticker) %>
                    10 stocks
                <% end %>
                <% if current_user.stock_alredy_tracked?(@stock.ticker) %>
                    this stock
                <% end %>
            </li>
        <% end %>
    </ul>
    </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'users/result.html' %>"

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
    <h3>Search Stocks</h3> 
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
<div id="results" class="error_msg">
</div>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <%=  'You are currently not tracking any stocks' %>
<% end %>

app/views/users/show.html.erb
<h2><%= "#{@user.full_name} Profile" %> </h2>

<div class="card col-sm-6 pl-0">
    <div class="card-body">
        <strong>Name: </strong><%= @user.full_name %>  <strong>Email: </strong><%= @user.email %>  
        <% if current_user.already_friend?(@user.id) %>
            <span class="badge badge-primary">
                <%= ' You are friends' %>
            </span>
        <% else %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user), class: "btn btn-success", method: :post %>
        <% end %>
    </div>
</div>
<p></p>
<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <span class="badge badge-primary">
        <%=  'This user currently not tracking any stocks' %>
    </span>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Stock App</h1>
<p></p>
<p>Currently most active stocks are: </p>
<div class="row">
    <div class="col-sm-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Last_Price</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @list_stock.each do |stock| %>
                <tr>
                    <th scope="row"><%= stock.symbol %></th>
                    <td><%= stock.company_name %></td>
                    <td><%= stock.latest_price %></td>
                    <td>
                        <% if !user_signed_in? %>
                           <%= link_to 'Add to portfolio', user_session_path, class: "btn btn-outline-success" %>
                        <% elsif current_user.can_track_stock?(stock.symbol) %>
                           <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, stock: stock.symbol), class: "btn btn-success", method: :post %>
                        <% else %>
                                You are already tracking
                                <% if !current_user.under_stock_limit? && !current_user.stock_alredy_tracked?(stock.symbol) %>
                                    10 stocks
                                <% end %>
                                <% if current_user.stock_alredy_tracked?(stock.symbol) %>
                                    this stock
                                <% end %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>